### ISSUE TITLE
关于 all 回显的建议

### ISSUE THREAD

**Issue by Nambers** [travellings-link/travellings-node#1]
> 不知道是不是姿势有误, 我 https://api.travellings.cn/all 访问的和这里的不太一样 :/  本来直接 pr 了 ()

就 link 项可以被做成链接, 然后状态可以分颜色显示，就好看一点。

**Comment by BLxcwg666** [comment]
目前这个是正在开发的后端，还没有正式上线（qwq
感谢您的建议，我们将在下个版本更新

**Comment by Nambers** [comment]
> 目前这个是正在开发的后端，还没有正式上线（qwq 感谢您的建议，我们将在下个版本更新

okok, 然后貌似 fetch 的查询字段有 sql 注入风险? (不太确定，没怎么打过 sql

**Comment by BLxcwg666** [comment]
> > 目前这个是正在开发的后端，还没有正式上线（qwq 感谢您的建议，我们将在下个版本更新
> 
> okok, 然后貌似 fetch 的查询字段有 sql 注入风险? (不太确定，没怎么打过 sql

感谢提醒，明天我看看
